Repository TYPO3-Documentation/render-guides, pull requests merged in 2023-12, with the labels that each got.

#203 [TASK] Dissolve component_docutils
  packages/typo3-docs-theme/assets/sass/_component_docutils.scss
  packages/typo3-docs-theme/assets/sass/_component_page.scss
  packages/typo3-docs-theme/assets/sass/components/_permalink.scss
  packages/typo3-docs-theme/assets/sass/theme.scss
  packages/typo3-docs-theme/resources/public/css/theme.css
Labels: styles

#208 [TASK] New styling for version directives
  packages/typo3-docs-theme/assets/sass/_component_rst.scss
  packages/typo3-docs-theme/assets/sass/_component_versionchanged.scss
  packages/typo3-docs-theme/assets/sass/theme.scss
  packages/typo3-docs-theme/resources/public/css/theme.css
  packages/typo3-docs-theme/resources/template/body/version-change.html.twig
Labels: styles

#232 [DOCS] Adapt path to Documentation folder on migration
  Documentation/Migration/Index.rst
Labels: documentation

#236 [CI] Let dependabot create PRs for updating dependencies
  .github/dependabot.yml
Labels: dependencies

#261 [TASK] Separate between live and development dependencies
  packages/typo3-docs-theme/package-lock.json
  packages/typo3-docs-theme/package.json
Labels: dependencies

#265 [TASK] Return DTO instead of array as processing result of migration
  packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
  packages/typo3-guides-cli/src/Migration/Dto/ProcessingResult.php
  packages/typo3-guides-cli/src/Migration/Processor.php
  packages/typo3-guides-cli/tests/unit/Command/MigrateSettingsCommandTest.php
  packages/typo3-guides-cli/tests/unit/Migration/ProcessorTest.php
Labels: refactoring

#263 [TASK] Give feedback on copying code block
  packages/typo3-docs-theme/assets/js/code-clipboard.js
  packages/typo3-docs-theme/assets/sass/components/_code.scss
  packages/typo3-docs-theme/resources/public/css/theme.css
  packages/typo3-docs-theme/resources/public/js/theme.min.js
  packages/typo3-docs-theme/resources/template/body/code.html.twig
  tests/Integration/tests/code-block/directive-only/expected/index.html
  tests/Integration/tests/code-block/with-caption/expected/index.html
  tests/Integration/tests/code-block/with-classes/expected/index.html
  tests/Integration/tests/code-block/with-emphasize-lines/expected/index.html
  tests/Integration/tests/code-block/with-language-aliases/expected/index.html
  tests/Integration/tests/code-block/with-language-rst/expected/index.html
  tests/Integration/tests/code-block/with-language-typoscript/expected/index.html
  tests/Integration/tests/code-block/with-language/expected/index.html
  tests/Integration/tests/code-block/with-line-number-start/expected/index.html
  tests/Integration/tests/code-block/with-line-numbers/expected/index.html
  tests/Integration/tests/configuration/expected/index.html
  tests/Integration/tests/markdown/expected/README.html
  tests/Integration/tests/tabs/expected/index.html
Labels: enhancement
