Repository TYPO3-Documentation/render-guides, pull requests merged in 2024-03, with the labels that each got.

#356 [FEATURE] Add list of available languages for code blocks
  composer.json
  composer.lock
  packages/typo3-docs-theme/composer.json
  packages/typo3-docs-theme/resources/template/body/directive/guides/codeblock-languages.html.twig
  tests/Integration/tests/codehighlight-languages/expected/index.html
  tests/Integration/tests/codehighlight-languages/input/index.rst
Labels: enhancement

#385 [TASK] Restyle admonitions
  packages/typo3-docs-theme/assets/sass/_variables.scss
  packages/typo3-docs-theme/assets/sass/components/directives/_admonition.scss
  packages/typo3-docs-theme/resources/public/css/theme.css
  packages/typo3-docs-theme/resources/template/body/admonition.html.twig
  tests/Integration/tests/admonitions/expected/index.html
  tests/Integration/tests/admonitions/input/index.rst
Labels: styles

#389 [BUGFIX] Fix display of top search
  packages/typo3-docs-theme/resources/template/structure/layoutParts/pageHeader.html.twig
  tests/Integration/tests-full/edit-on-github/expected/index.html
  tests/Integration/tests-full/edit-on-github/expected/page1.html
  tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
  tests/Integration/tests-full/index/expected/index.html
  tests/Integration/tests-full/link-wizard/expected/index.html
  tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
  tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
  tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
  tests/Integration/tests-full/menu-subpages/expected/index.html
  tests/Integration/tests-full/meta-data/expected/index.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
  tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
  tests/Integration/tests-full/next-prev/expected/index.html
  tests/Integration/tests-full/next-prev/expected/page.html
  tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
  tests/Integration/tests-full/page-with-subpages/expected/index.html
  tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
  tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
  tests/Integration/tests-full/two-toctrees/expected/index.html
Labels: styles

#395 [TASK] Streamline documentation for subtree-split repositories
  packages/typo3-docs-theme/README.rst
  packages/typo3-guides-cli/README.rst
  packages/typo3-guides-extension/README.rst
  packages/typo3-version-handling/README.rst
Labels: documentation

#449 [BUGFIX] Use simple PHP container for rendertest and test-docs
  Makefile
Labels: bug
